apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
    app: digimon-db
  name: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: digimon-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
        app: digimon-db
    spec:
      containers:
        - image: core.harbor.domain/devops/digimon-db
          imagePullPolicy: Always
          name: db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
