apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: envoy
  name: envoy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9901"
    port: 9901
    targetPort: 9901
  selector:
    io.kompose.service: envoy
status:
  loadBalancer: {}
