apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
    - host: web.backend.com
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 8060
    - host: api.backend.com
      http:
        paths:
          - backend:
              serviceName: envoy
              servicePort: 8080
