apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
    app: digimon-web
  name: web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: digimon-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
        app: digimon-web
    spec:
      containers:
        - image: core.harbor.domain/devops/digimon-web
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
